name: Build & Release

on:
  workflow_call:
    inputs:
      major_tag:
        required: true
        type: string
      minor_tag:
        required: true
        type: string
      patch_tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      NAME: tv-control-${{ matrix.os }}-${{ matrix.arch }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.patch_tag }}

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Build Binary
      run: |
        mkdir -p dist
        go build -o dist/${{ env.NAME }}
    
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}
        path: dist/${{ env.NAME }}

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish Release (Major)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          tag_name: ${{ inputs.major_tag }}
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release (Minor)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          tag_name: ${{ inputs.minor_tag }}
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release (Patch)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          tag_name: ${{ inputs.patch_tag }}
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
