name: CD

on:
  push:
    branches:
      - main
    tags:
      - "v.*.*.*"

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      NAME: tv-control-${{ matrix.os }}-${{ matrix.arch }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Build Binary
      run: |
        mkdir -p dist
        go build -o dist/${{ env.NAME }}
    
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.NAME }}
        path: dist/${{ env.NAME }}

  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

