name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-Checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Check Formatting
      run: test -z "$(go fmt .)"
    
    - name: Run Tests
      run: go test ./...