name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-Checks:
    runs-on: ubuntu-latest
    env:
      REQUIRED_COVERAGE: 70
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Check Formatting
      run: test -z "$(go fmt .)"
    
    - name: Run Tests
      run: go test -coverprofile=coverage.out -v ./...

    - name: Check Test Coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
        echo "Total coverage: $coverage%"
        awk -v cov="$coverage" -v th=${{ env.REQUIRED_COVERAGE }} 'BEGIN { if (cov < th) { exit 1 } }'
